import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "./StoreProvider";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Algo&Stock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
        data-new-gr-c-s-check-loaded="14.1246.0"
        data-gr-ext-installed=""
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
